---
- name: reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: restart web-app service
  become: true
  systemd:
    name: "{{ web_app_service_name }}"
    state: restarted
    enabled: true